name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun ci

      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      #   with:Client HTML-Validate: connection to server is erroring. write EPIPE
      #     name: build-output
      #     path: ./dist

      - name: Publish to npm
        run: bunx npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Publish to npm
    # - run: bunx npm publish --access public --registry https://registry.npmjs.org/
    #   env:
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
